source "https://github.com/CocoaPods/Specs.git"
platform :ios, "8.0"
use_frameworks!

target "NewsAPIDemo" do
pod 'SnapKit', '~> 3.1.2'
pod 'Kingfisher', '~>3.3.4'
pod 'Alamofire', '~> 4.3.0'
pod 'SwiftyJSON', '~> 3.1.4'
end

